mainModule:
  url: http://127.0.0.1/registerslaves

currentModule:
  inputUrl: 127.0.0.1/
  mainUrl: http://www.homes.bg
  sourceName: homes.bg

server:
  port: 80

logging:
  file: app.log
  level:
    com.musala.content: DEBUG

