mainModule:
  registerUrl: http://localhost:8080/register
  contentUrl: http://localhost:8080/content
  queueUrl: http://localhost:8080/queue

currentModule:
  moduleUrl: http://localhost:8081/
  mainUrl: http://www.homes.bg/
  sourceName: homes.bg

server:
  port: 8081

logging:
  file: app.log
  level:
    root: OFF
    com.musala.content: DEBUG

